Travelperk Integrations: Initial Commit
fylein/fyle-integrations-settings-api pull request #27
Opened 2023-01-16 09:28 UTC by NileshPant1999

2023-01-24 07:33 UTC, Shwetabhk commented on apps/travelperk/models.py
> +    is_s3_connected = models.BooleanField(null=True, help_text='If S3 Is Connectoed')
why do we need this?

2023-01-24 07:34 UTC, Shwetabhk commented on apps/travelperk/models.py
> +    recipe_status = models.BooleanField(help_text='recipe status', null=True)
if the field is boolean then the name `recipe_status` doesn't make sense
it should be is_recipe_enabled or something

2023-01-24 07:35 UTC, Shwetabhk commented on apps/travelperk/serializers.py
> +                'recipe_status': True,
is_recipe_enabled

2023-01-24 07:38 UTC, Shwetabhk commented on apps/travelperk/urls.py
> +    path('s3_connection/', AwsS3Connection.as_view(), name='s3-connection')
y dis?

2023-01-24 07:38 UTC, Shwetabhk commented on apps/travelperk/views.py
> +    def post(self, request, *args, **kwargs):
y dis

2023-01-24 07:39 UTC, Shwetabhk requested changes
Please make changes to comments

2023-01-24 09:48 UTC, NileshPant1999 commented on apps/travelperk/models.py
> +    is_s3_connected = models.BooleanField(null=True, help_text='If S3 Is Connectoed')
@Shwetabhk we need this as we need to establish this connection in workato recipe, this is nothing but just a normal http connection the name can be misleading do you want me to change it ??

2023-01-24 09:48 UTC, NileshPant1999 commented on apps/travelperk/models.py
> +    recipe_status = models.BooleanField(help_text='recipe status', null=True)
sure will change it.

2023-01-30 05:42 UTC, Shwetabhk approved these changes

2023-01-31 13:48 UTC, merged